-- phpMyAdmin SQL Dump
-- version 4.9.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Sep 14, 2020 at 08:37 PM
-- Server version: 10.4.8-MariaDB
-- PHP Version: 7.1.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `amazing-grazing`
--

-- --------------------------------------------------------

--
-- Table structure for table `card_information`
--

CREATE TABLE `card_information` (
  `card_id` int(11) NOT NULL,
  `card_type` varchar(500) NOT NULL,
  `card_preview` varchar(500) NOT NULL,
  `card_title` varchar(500) NOT NULL,
  `card_text` varchar(1300) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `card_information`
--

INSERT INTO `card_information` (`card_id`, `card_type`, `card_preview`, `card_title`, `card_text`) VALUES
(1, 'beef cattle', 'Maintain balance between protecting grasslands and keeping your beef cattle numbers high.', '', ''),
(2, 'beef cattle', 'Patch-burn grazing technique is advised to be used.', '', ''),
(3, 'beef cattle', 'Burn grassland not only for the beef cattle. Grasslands require planned burning.', 'Burn grasslands and increase livestock', '<img style=\"width: 100%;\" src=\"images/livestock_stats/beef-card-1.jpeg\" alt=\"Burn grasslands and increase livestock\"><h5 class=\"text-justify\">Conduct controlled dry season burning to stimulate fresh plant growth to restore calcium to the soil that builds up in the dry grasses. Some species of native plants need occasional fire to thrive, while blazes can also help remove invasive species.</h5><p></p><h5 class=\"text-justify\">Fire is important for grasslands’ existence. They prevent woody plants from spreading and enable the grass to re-grow, becoming thicker, more resilient and healthier. How do grasses survive these fires? They have developed extensive underground systems during the course of evolution, which allow them to burst back to life, stronger than ever before, fairly quickly after a fire.</h5>'),
(4, 'beef cattle', 'Droughts and too much humid negatively affect grasslands and beef cattle.', 'Keep grasslands fresh', '<img style=\"width: 100%;\" src=\"images/livestock_stats/beef-card-2.jpeg\" alt=\"Keep grasslands fresh\"><h5 class=\"text-justify\">All grasslands get a specific amount of yearly rainfall, depending on their exact location in the world. What you did not know is that if grasslands receive much less rain than ordinarily, it would become a desert, and if it got much more rain than usually, it would eventually turn into a forest. That is also the reason why grasslands are often located between deserts and forests – these nearby areas get less or more rain, and have thus developed into something else.</h5><p><p><h5>provide solution perhaps?</h5>'),
(5, 'beef cattle', 'Just like grasslands, beef cattle is involved in the whole biomass and generates numerous by-products.', 'Beef cattle provides hundreds by-products', '<img style=\"width: 100%;\" src=\"images/livestock_stats/beef-card-3.jpg\" alt=\"Beef cattle provides hundreds by-products\"><h5 class=\"text-justify\">Over 98% of the beef animal is used when it is processed. Besides meat and milk, beef cattle provide us with hundreds of important by-products. About 45% of the animal is used for meat and the rest is used for other by-products including leather, china, glue, film, soap, pharmaceuticals, insulin, gelatins, etc. Almost the entire beef animal can be used in some way. From a typical 454-kilogram steer, slightly over 40% of the animal is used for retail beef and the remaining 60% is processed into by-products.</h5>'),
(6, 'Dairy cattle', 'Protecting grasslands is important but lack of dairy cattle will lead to lack of milk supply.', '', ''),
(7, 'Dairy cattle', 'Rotational grazing technique is advised to be used.', '', ''),
(8, 'Dairy cattle', 'Kangaroos negatively affect grasslands development and dairy cattle.', 'Keep kangaroos away from grassland', '<img style=\"width: 100%;\" src=\"images/livestock_stats/dairy-card-1.jpeg\" alt=\"Keep kangaroos away from grasslands\"><h5 class=\"text-justify\">Kangaroo numbers need to be controlled due to threatening one of Australia’s last remaining original grasslands and endangered livestock. Australian Department of Defence is currently culling hundreds of kangaroos on the outskirts of the capital Canberra that have produced heated discussions and hit international headlines. Australia’s iconic animal has multiplied so much over recent years that Canberra has three times as many kangaroos as inhabitants. The situation is particularly critical at two enclosed military sites on the outskirts of the city, which form an ideal refuge for the eastern grey kangaroo (Macropus giganteus)</h5>'),
(9, 'Dairy cattle', 'Just like grasslands, dairy cattle need rest in their life cycle.', 'Provide enough rest for dairy cattle', '<img style=\"width: 100%;\" src=\"images/livestock_stats/dairy-card-2.jpeg\" alt=\"Provide enough rest for dairy cattle\"><h5 class=\"text-justify\">Generally, a cow can produce milk in 9-10 months each year according to pregnancy. Many ranchers run cow-calf operations. The cows are bred to calve in the spring or fall that keeps a herd of cows to produce calves. The natural life expectancy of a cow is twenty years. Some get up to 25 years old. Cows, like our grassland that need certain time to rest and regrowth for healing and better productivity. Therefore, we recommend you take sustainable techniques like rotational grazing and patch-burn to rest the land.</h5>'),
(10, 'Dairy cattle', 'Make sure the right grazing technique is used to provide enough food.', 'Keep dairy cattle fed', '<img style=\"width: 100%;\" src=\"images/livestock_stats/dairy-card-3.jpeg\" alt=\"Keep dairy cattle fed\"><h5 class=\"text-justify\">A cow, that is milking, eats about 45 kilograms of feed each day. Cows drink a whole bathtub of water in just one day. That’s why cows are considered as the competitive eater and ultimate recyclers. The feed is typically a combination of grass, grain, and a mixture of other ingredients like citrus pulp, almond hulls and cotton seeds. These are items that may otherwise be thrown away. The ingredients, that we cannot eat, can often be nutritious for them. Farmers employ professional animal nutritionists to develop scientifically formulated, balanced, and nutritious diets for their cows.</h5>'),
(11, 'Milk', 'Reduction of dairy livestock leads to extreme reduction of milk quantity.', '', ''),
(12, 'Milk', 'Rotational grazing technique is advised to be used.', '', ''),
(13, 'Milk', 'Ensure that suitable grasslands are selected, and appropriate grazing techniques are used.', 'Maintain grasslands well', '<img style=\"width: 100%;\" src=\"images/livestock_stats/milk-card-1.jpeg\" alt=\"Maintain grasslands well\"><h5 class=\"text-justify\">Although grass is without a doubt the most important feature of grasslands, it doesn’t grow all the time, at least not in temperate grasslands that are most common in Earth’s mid-latitude, such as America’s prairies and Europe’s steppes.</h5><p></p><h5 class=\"text-justify\">Life in temperate grasslands is forced to survive in two very different seasons: the growing season and the dormant season. While the growing season allows the flora of the grasslands to thrive, the climate is too cold during the dormant season.</h5>'),
(14, 'Milk', 'Two-way effects! Estimate the value of environmental impacts of dairy farming.', 'Estimate the value of environmental impacts of dairy farming', '<img style=\"width: 100%;\" src=\"images/livestock_stats/milk-card-2.jpeg\" alt=\"Estimate the value of environmental impacts of dairy farming\"><h5 class=\"text-justify\">The intensification and expansion of dairy farms have contributed to many environmental problems such as the contamination of ground and surface water, insufficient water for irrigation during droughts, excess nutrient losses from farms, larger emissions of greenhouse gases. Permanent grassland farms can generally keep up with fodder-crop farms, even in an intensive production setting. However, extensively operating farms, especially those on permanent grassland, significantly lag behind in productivity.</h5>'),
(15, 'Sheep', 'Sheep are the most dominate livestock in Australia and its reduction will negatively affect Australian economy.', '', ''),
(16, 'Sheep', 'Seasonal grazing technique is adviced to be used.', '', ''),
(17, 'Sheep', 'Rabbits can be a cause of decreasing number of sheep.', 'Beware of rabbits', '<img style=\"width: 100%;\" src=\"images/livestock_stats/sheep-card-1.jpeg\" alt=\"Beware of rabbits\"><h5 class=\"text-justify\">Rabbits compete with native animals and domestic livestock for food and shelter, increasing grazing pressure and lowering the land’s carrying capacity.</h5><p></p><h5 class=\"text-justify\">Rabbits act as a food source for introduced predators, which can lead to increased lamb losses and disease prevalence.</h5>'),
(18, 'Sheep', 'Sheep are light eaters compared to cattle, but their density is much higher.', 'High density of sheeps negatively affect grassland', '<img style=\"width: 100%;\" src=\"images/livestock_stats/sheep-card-2.jpeg\" alt=\"High density of sheeps negative affect grassland\"><h5 class=\"text-justify\">Large density causes lots of damage to the grass and the plants in the area. Though, sheep are herbivores, which means their diet does not include meat. They typically eat seeds, grass and plants. Some sheep do not need much water. The desert bighorn sheep, for example, gets most of its water from eating plants. Like all ruminants, they have multi-chambered stomachs that are adapted to ferment cellulose before digestion. To completely digest their food, sheep will regurgitate their food into their mouths, rechew and swallow. This regurgitated food is called cud.</h5>'),
(19, 'Wool', 'Rapid increase in reduction of wool will eventually lead to depletion, loss of income, and reduction of cloths.', '', ''),
(20, 'Wool', 'Seasonal grazing technique is advised to be used.', '', ''),
(21, 'Wool', 'Ensure that grasslands gets enough water to provide nutrients to sheep.', 'Keep grasslands moist', '<img style=\"width: 100%;\" src=\"images/livestock_stats/wool-card-1.jpeg\" alt=\"Keep grasslands moist\"><h5 class=\"text-justify\">Where there are plants, there also must be moisture in the soil, and grasslands with their various kinds of grasses, shrubbery and even occasional trees are no different. But the relationship of grasslands and rain is a complicated one. All types of grasslands need a certain amount of rain, but then again not too much rain, since that will cause them to transform into something else.</h5><p></p><h5 class=\"text-justify\">How much rain is too much rain? How much is too little? That depends on the type of grassland and its location, but grasslands in general get around 50 to 90 centimeters of annual rainfall. Some grasslands also exist in areas where the annual rainfall exceeds 120 centimeters annually, and some exist in areas where there is as little as 25 centimeters of annual rainfall.</h5>'),
(22, 'Wool', 'Wool is a treasure in Australia because it helps us to win Guinness World Record.', 'Aussie won the Guinness World Record', '<img style=\"width: 100%;\" src=\"images/livestock_stats/wool-card-2.jpeg\" alt=\"Aussie won the Guinness World Record\"><h5 class=\"text-justify\">Hilton Barrett who from Australian holds the Guinness World Record for the fastest time to shear a single mature sheep at an amazing 39.31 seconds. The record was set at the Wellington Show 2010 in Wellington, New South Wales on 1 May 2010. Wool fibers are very durable and flexible. Wool fiber can withstand being bent 20,000 times without breaking. In comparison, cotton breaks after 3,000 bends and silk after 2,000 bends. Also, Sheep wool has an incredible, natural UV protection built right in, which helps to keep sheep and lambs from getting sunburnt.</h5>'),
(23, 'Land', 'The less land is used - the better it is for Australian grasslands, though it negatively affects people.', '', ''),
(24, 'Land', 'Grazing techniques are advised to be used.', '', ''),
(25, 'Land', 'Animals, just like humans, are involved in overgrazing the grasslands.', 'Animals, just like humans, are cause of overgrazing', '<img style=\"width: 100%;\" src=\"images/livestock_stats/land-card-1.jpeg\" alt=\"Animals, just like humans, are cause of overgrazing\"><h5 class=\"text-justify\">Rabbit can cause overgrazing native and sown pastures, leading to loss of plant biodiversity and reduced crop yields. Because they are too much and eat too fast, they are preventing or inhibiting the regeneration of native shrubs and trees by grazing.</h5><p></p><h5 class=\"text-justify\">Moreover, they build warrens and it causes land degradation and erosion, also increasing and spreading invasive weeds. they cause huge damage to our land; numbers need to be controlled.</h5>'),
(26, 'Land', 'The right balanced is needed to preserve Australian grasslands.', 'Maintain balance in the use of the land', '<img style=\"width: 100%;\" src=\"images/livestock_stats/land-card-2.jpeg\" alt=\"Maintain balance in the use of the land\"><h5 class=\"text-justify\">Australia has unique land, water, vegetation and biodiversity resources. Australia’s 7.7 million square kilometres support a wide range of agricultural and forestry industries. Production from natural resources earns over $38 billion a year in exports from agriculture, fisheries and forestry. Competitive pressures drive the need for improved productivity, which includes increased diversification and intensification. These trends are occurring against a background of increased climate variability.</h5><p></p><h5 class=\"text-justify\">The way in which land is used has a profound effect on Australia’s social and ecological systems. There is a strong link between changes in land use and environmental, economic and social conditions. Information on land use and management is fundamental to understanding landscapes, agricultural production and the management of natural resources.</h5>'),
(27, 'Meat', 'Reduction of beef cattle negatively affects the quantity of the beef produced and will have a negative impact in a long run.', '', ''),
(28, 'Meat', 'Patch-burn grazing technique is adviced to be used.', '', ''),
(29, 'Meat', 'Grass fed or grain fed beef? The differences and impacts are significant.', 'Grass fed or grain fed beef?', '<img style=\"width: 100%;\" src=\"images/livestock_stats/meat-card-1.jpeg\" alt=\"Grass fed or grain fed beef?\"><h5 class=\"text-justify\">Grass fed beef meat comes from cattle that have only grazed on grass. They feed on a range of different types of grasses, depending on climate and region. In Australia, cattle are predominantly grass fed and account for around 2/3 of whole beef production on average. Grain fed beef comes from cattle which are fed grass for most of their lives and then transition to grain-based diets for the remainder of their lives. The number of days during which they are fed a grain-based diet varies.</h5><p></p><h5 class=\"text-justify\">Livestock are fed grain for several reasons, including to maintain a consistent meat supply, improve eating quality, meet specific needs for niche markets (e.g. for highly marbled meat), meet the energy needs of animals when pasture is limited (such as in drought conditions) and increase animal size.</h5>'),
(30, 'Meat', 'People in the industry. The major group to make the changes!', 'People make a difference', '<img style=\"width: 100%;\" src=\"images/livestock_stats/meat-card-2.jpeg\" alt=\"People make a difference\"><h5 class=\"text-justify\">There are 41,800 agricultural businesses maintained in the cattle industry and 26.4 million head of cattle in Australia as of 2017-2018. Around 172,000 people are employed in the red meat industry, including on-farm production, processing and retail. In 2018-2019, Australia produced approximately 2.35 million tones carcass weight (cwt) of beef and veal. In 2018-2019, 3.14 million grain fed cattle were marketed 38% of all adult cattle slaughtered. On the other hand, the gross value of Australian cattle and calf production (including live cattle exports) in 2018-19 is estimated at A$10.9 billion. Cattle contributed 18% of the total farm value of A$61.4 billion in 2018-2019.</h5>'),
(31, 'Yarn', 'Reduction of sheep negatively affects the production of wool, which at the end negatively affect production of yarn.', '', ''),
(32, 'Yarn', 'Seasonal grazing technique is adviced to be used.', '', ''),
(33, 'Yarn', 'Reduction of yarn will cause reduction of cloths.', 'Production of cloths is affected', '<img style=\"width: 100%;\" src=\"images/livestock_stats/yarn-card-1.jpg\" alt=\"\"><h5 class=\"text-justify\">Even though wool represents only 1.2% of the virgin fibre supply, it represents about 5% of clothing donated to charity. Wool-made yarn is also one of the most sought after recycled textiles for converting into new long-lasting products, such as garments, mattresses and upholstery. In contrast to synthetics, wool-made yarn can absorb moisture vapour which means less sweat on your body.  Wool-made yarn even absorbs the odour molecules from sweat, which are only released upon washing. Wool-made yarn inherent chemical structure makes wool naturally flame resistant. It is a highly trusted natural fibre in public areas such as hotels, aircraft, hospitals and theatres.</h5>'),
(34, 'Yarn', 'Few other reasons behind yarn decline.', 'Reasons behind yarn reduction', '<img style=\"width: 100%;\" src=\"images/livestock_stats/yarn-card-2.jpg\" alt=\"\"><h5 class=\"text-justify\">The best wool goes to make suits and clothing, not yarn. There were several factors that contributed to the yarn industry decline.  Firstly, the Australian government began reducing the tariff protection in the footwear, clothing and textile industries in the 1970s, which opened the way for cheap imports to increasingly flood the Australian market. Now we all know that this affected all sectors of manufacturing. Prior to the removal of the tariffs, many larger towns in Australia had mills - it’s important to remember not all of these mills made yarn for the hand knitter, again this was a small proportion of the mills - many made fabrics, carpets, and yarns specifically for the manufacturing sector. It was the tariff reductions coupled with the changing directions worldwide of trends, that put our yarn industry into serious damage control.  In the 1980s people began to turn their back on handicrafts viewing them as old fashioned; a bit daggy. Pattern and yarn sales slumped, and many local yarn stores closed. You could also, for the first time, buy a machine-knitted jumper for cheaper than you could knit one.</h5>'),
(35, 'Total', 'Beef and dairy cattle, and sheep livestock is reducing yearly and will eventually reach zero.', '', ''),
(36, 'Total', 'Grazing techniques are adviced to be used.', '', ''),
(37, 'Total', 'Burn grassland not only for the beef cattle. Grasslands require planned burning.', 'Burn grasslands and increase livestocks', '<img style=\"width: 100%;\" src=\"images/livestock_stats/beef-card-1.jpeg\" alt=\"Burn grasslands and increase livestocks\"><h5 class=\"text-justify\"><h5 class=\"text-justify\">Conduct controlled dry season burning to stimulate fresh plant growth to restore calcium to the soil that builds up in the dry grasses. Some species of native plants need occasional fire to thrive, while blazes can also help remove invasive species.</h5><p></p><h5 class=\"text-justify\">Fire is important for grasslands’ existence. They prevent woody plants from spreading and enable the grass to re-grow, becoming thicker, more resilient and healthier. How do grasses survive these fires? They have developed extensive underground systems during the course of evolution, which allow them to burst back to life, stronger than ever before, fairly quickly after a fire.'),
(38, 'Total', 'Droughts and too much humid negatively affect grasslands and beef cattle.', 'Keep grasslands fresh', '<img style=\"width: 100%;\" src=\"images/livestock_stats/beef-card-2.jpeg\" alt=\"Keep grasslands fresh\"><h5 class=\"text-justify\"><h5 class=\"text-justify\">All grasslands get a specific amount of yearly rainfall, depending on their exact location in the world. What you didn not know is that if grasslands receive much less rain than ordinarily, it would become a desert, and if it got much more rain than usually, it would eventually turn into a forest. That is also the reason why grasslands are often located between deserts and forests – these nearby areas get less or more rain, and have thus developed into something else.</h5>'),
(39, 'Total', 'Just like grasslands, beef cattle is involved in the whole biomass and generates numerous by-products.', 'Beef cattle provides hundreds by-products', '<img style=\"width: 100%;\" src=\"images/livestock_stats/beef-card-3.jpg\" alt=\"Beef cattle provides hundreds by-products\"><h5 class=\"text-justify\"><h5 class=\"text-justify\">Over 98% of the beef animal is used when it is processed. Besides meat and milk, beef cattle provide us with hundreds of important by-products. About 45% of the animal is used for meat and the rest is used for other by-products including leather, china, glue, film, soap, pharmaceuticals, insulin, gelatines, etc. Almost the entire beef animal can be used in some way. From a typical 454-kilogram steer, slightly over 40% of the animal is used for retail beef and the remaining 60% is processed into by-products.</h5>'),
(40, 'Total', 'Kangaroos negatively affect grasslands development and dairy cattle.', 'Keep kangaroos away from grasslands', '<img style=\"width: 100%;\" src=\"images/livestock_stats/dairy-card-1.jpeg\" alt=\"Keep kangaroos away from grasslands\"><h5 class=\"text-justify\"><h5 class=\"text-justify\">Kangaroo numbers need to be controlled due to threatening one of Australia’s last remaining original grasslands and endangered livestock. Australian Department of Defence is currently culling hundreds of kangaroos on the outskirts of the capital Canberra that have produced heated discussions and hit international headlines. Australia’s iconic animal has multiplied so much over recent years that Canberra has three times as many kangaroos as inhabitants. The situation is particularly critical at two enclosed military sites on the outskirts of the city, which form an ideal refuge for the eastern grey kangaroo (Macropus giganteus)</h5>'),
(41, 'Total', 'Just like grasslands, dairy cattle need rest in their life cycle.', 'Provide enough rest for dairy cattle', '<img style=\"width: 100%;\" src=\"images/livestock_stats/dairy-card-2.jpeg\" alt=\"Provide enough rest for dairy cattle\"><h5 class=\"text-justify\"><h5 class=\"text-justify\">Generally, a cow can produce milk in 9-10 months each year according to pregnancy. Many ranchers run cow-calf operations. The cows are bred to calve in the spring or fall that keeps a herd of cows to produce calves. The natural life expectancy of a cow is twenty years. Some get up to 25 years old. Cows, like our grassland that need certain time to rest and regrowth for healing and better productivity. Therefore, we recommend you take sustainable techniques like rotational grazing and patch-burn to rest the land.</h5>'),
(42, 'Total', 'Make sure the right grazing technique is used to provide enough food.', 'Keep dairy cattle fed', '<img style=\"width: 100%;\" src=\"images/livestock_stats/dairy-card-3.jpeg\" alt=\"Keep dairy cattle fed\"><h5 class=\"text-justify\"><h5 class=\"text-justify\">A cow, that is milking, eats about 45 kilograms of feed each day. Cows drink a whole bathtub of water in just one day. That’s why cows are considered as the competitive eater and ultimate recyclers. The feed is typically a combination of grass, grain, and a mixture of other ingredients like citrus pulp, almond hulls and cotton seeds. These are items that may otherwise be thrown away. The ingredients, that we cannot eat, can often be nutritious for them. Farmers employ professional animal nutritionists to develop scientifically formulated, balanced, and nutritious diets for their cows.</h5>'),
(43, 'Total', 'Rabbits can be a cause of decreasing number of sheep.', 'Beware of rabbits', '<img style=\"width: 100%;\" src=\"images/livestock_stats/sheep-card-1.jpeg\" alt=\"Beware of rabbits\"><h5 class=\"text-justify\"><h5 class=\"text-justify\">Rabbits compete with native animals and domestic livestock for food and shelter, increasing grazing pressure and lowering the land’s carrying capacity.</h5><p></p><h5 class=\"text-justify\">Rabbits act as a food source for introduced predators, which can lead to increased lamb losses and disease prevalence.</h5>'),
(44, 'Total', 'Sheep are light eaters compared to cattle, but their density is much higher.', 'High density of sheeps negative affect grassland', '<img style=\"width: 100%;\" src=\"images/livestock_stats/sheep-card-2.jpeg\" alt=\"High density of sheeps negative affect grassland\"><h5 class=\"text-justify\"><h5 class=\"text-justify\">Large density causes lots of damage to the grass and the plants in the area. Though, sheep are herbivores, which means their diet does not include meat. They typically eat seeds, grass and plants. Some sheep do not need much water. The desert bighorn sheep, for example, gets most of its water from eating plants. Like all ruminants, they have multi-chambered stomachs that are adapted to ferment cellulose before digestion. To completely digest their food, sheep will regurgitate their food into their mouths, rechew and swallow. This regurgitated food is called cud.</h5>');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `card_information`
--
ALTER TABLE `card_information`
  ADD PRIMARY KEY (`card_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `card_information`
--
ALTER TABLE `card_information`
  MODIFY `card_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=45;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
